name: "Nightly Build"
run-name: "Nightly Build ${{ github.run_number }}"

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  generate-changelog:
    runs-on: ubuntu-latest
    outputs:
      changelog: ${{ steps.generate.outputs.changelog }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - id: generate
        run: |
          changelog=$(./.github/scripts/generate-changelog.sh)
          echo "changelog<<EOF" >> $GITHUB_OUTPUT
          echo "${changelog}" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

  build:
    needs: generate-changelog
    permissions:
      contents: write
    uses: LiRenTech/turbo-tauri/.github/workflows/turbo-tauri.yml@master
    with:
      android_key_alias: "upload"
      android_key_path: "upload.jks"
      app_root: "app"
      app_version: "0.0.0-nightly.r${{ github.run_number }}"
      app_version_android: "0.0.${{ github.run_number }}"
      aur_key_algorithm: "ed25519"
      aur_package_name: "project-graph-nightly-bin"
      delete_release: true
      prerelease: true
      release_name: "Nightly Build ${{ github.run_number }}"
      release_notes: ${{ needs.generate-changelog.outputs.changelog }}
      release_tag: "nightly"
      task_build: "tauri:build"
      task_build_android: "tauri:build:android"
      turbo_team: "zty012"
    secrets:
      ANDROID_KEYSTORE: ${{ secrets.ANDROID_RELEASE_KEYSTORE }}
      ANDROID_KEYSTORE_PASSWORD: ${{ secrets.ANDROID_RELEASE_PASSWORD }}
      AUR_SSH_PRIVATE_KEY: ${{ secrets.AUR_SSH_PRIVATE_KEY }}
      BUILD_ENV: |
        LR_API_BASE_URL=${{ secrets.ENV_API_BASE_URL }}
        LR_GITHUB_CLIENT_SECRET=${{ secrets.ENV_GITHUB_CLIENT_SECRET }}
      TAURI_SIGNING_PRIVATE_KEY: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY }}
      TAURI_SIGNING_PRIVATE_KEY_PASSWORD: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY_PASSWORD }}
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
